In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mpl_toolkits
import datetime as dt
import operator
%matplotlib inline

/home/jobin/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [10]:
#constants and variable
x = tf.constant(-2.0, name="x", dtype=tf.float32)
a = tf.constant(5.0, name="a", dtype=tf.float32)
b = tf.constant(13.0, name="b", dtype=tf.float32)

y = tf.Variable(tf.add(tf.multiply(a, x), b))

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    print session.run(y)

3.0


In [11]:
#placeholder
x = tf.placeholder(tf.float32, name="x")
y = tf.placeholder(tf.float32, name="y")

z = tf.multiply(x, y, name="z")

with tf.Session() as session:
    print session.run(z, feed_dict={x: 2.1, y: 3.0})

6.2999997


In [14]:
x = tf.constant(-2.0, name="x", dtype=tf.float32)
a = tf.constant(5.0, name="a", dtype=tf.float32)
b = tf.constant(13.0, name="b", dtype=tf.float32)


y = tf.Variable(tf.add(tf.multiply(a, x), b))


init = tf.global_variables_initializer()


with tf.Session() as session:
    merged = tf.summary.merge_all() 
    writer = tf.summary.FileWriter("logs", session.graph)


    session.run(init)
    print session.run(y)

3.0


In [22]:
#1d array
tensor_1d = np.array([1.45, -1, 0.2, 102.1])
print tensor_1d

[  1.45  -1.     0.2  102.1 ]


In [21]:
#1d array to tensor
tensor_1d = np.array([1.45, -1, 0.2, 102.1])
tensor = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)
with tf.Session() as session:
    print session.run(tensor)
    print session.run(tensor[0])
    print session.run(tensor[1])

[  1.45  -1.     0.2  102.1 ]
1.45
-1.0


In [24]:
#2d matrix to tensor
tensor_2d = np.array(np.random.rand(4, 4), dtype='float32')
tensor_2d_1 = np.array(np.random.rand(4, 4), dtype='float32')
tensor_2d_2 = np.array(np.random.rand(4, 4), dtype='float32')

m1 = tf.convert_to_tensor(tensor_2d)
m2 = tf.convert_to_tensor(tensor_2d_1)
m3 = tf.convert_to_tensor(tensor_2d_2)
mat_product = tf.matmul(m1, m2)
mat_sum = tf.add(m2, m3)
mat_det = tf.matrix_determinant(m3)

with tf.Session() as session:
    print session.run(mat_product)
    print session.run(mat_sum)
    print session.run(mat_det)

[[1.1556089  0.5242052  1.3517512  0.96458447]
 [1.4411933  0.48925623 1.4353809  1.184251  ]
 [1.5245483  0.5869725  1.9662781  1.403646  ]
 [1.0356354  0.33383352 1.6011732  1.1223309 ]]
[[1.7312961  0.4338314  1.2200854  0.68333673]
 [0.31192312 0.933083   1.0124826  0.65248823]
 [1.0196934  0.66465926 1.1070616  1.1447706 ]
 [0.43804836 1.188235   1.8821197  1.780334  ]]
-0.27646232


In [37]:
#tensor operation
tensor_1d = np.array([30, 45, 60])
tensor = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)
with tf.Session() as session:
    print session.run(tf.cos(tensor))

[ 0.15425145  0.52532199 -0.95241298]


In [41]:
#matrix operations
def convert(v, t=tf.float32):
    return tf.convert_to_tensor(v, dtype=t)

m1 = convert(np.array(np.random.rand(4, 4), dtype='float32'))
m2 = convert(np.array(np.random.rand(4, 4), dtype='float32'))
m3 = convert(np.array(np.random.rand(4, 4), dtype='float32'))
m4 = convert(np.array(np.random.rand(4, 4), dtype='float32'))
m5 = convert(np.array(np.random.rand(4, 4), dtype='float32'))

m_tranpose = tf.transpose(m1)
m_mul = tf.matmul(m1, m2)
m_det = tf.matrix_determinant(m3)
m_inv = tf.matrix_inverse(m4)
m_solve = tf.matrix_solve(m5, [[1], [0], [0], [0]])

with tf.Session() as session:
    print session.run(m_tranpose)
    print session.run(m_mul)
    print session.run(m_inv)
    print session.run(m_det)
    print session.run(m_solve)

[[0.48436093 0.9834593  0.19419342 0.84315044]
 [0.05990237 0.9852567  0.5637786  0.7091128 ]
 [0.07944763 0.35905617 0.3865844  0.75230587]
 [0.7990572  0.7369079  0.18424805 0.37813088]]
[[0.67329884 0.5950659  0.57781434 0.5293169 ]
 [1.4576776  1.2872739  1.4553479  1.8918629 ]
 [0.56944215 0.6055926  0.6807114  0.89349097]
 [1.4324789  0.94283164 1.4826233  1.7713273 ]]
[[-0.27772272  2.8185878  -1.2093316  -0.95643055]
 [ 0.04973055 -0.38225576  1.3576034   0.01611672]
 [-0.14759703 -0.70805126  0.2589901   1.6895452 ]
 [ 2.425174   -3.6162348   0.34394744 -0.21964966]]
0.048482414
[[ 19.709417 ]
 [-35.97983  ]
 [  3.9968905]
 [  3.2959876]]


In [2]:
#sequence utilities
def convert(v, t=tf.float32):
    return tf.convert_to_tensor(v, dtype=t)

x = convert(np.array([
    [2, 2, 1, 3],
    [4, 5, 6, -1],
    [0, 1, 1, -2],
    [6, 2, 3, 0]
]))

y = convert(np.array([1, 2, 5, 3, 7]))
z = convert(np.array([1, 0, 4, 6, 2]))

arg_min = tf.argmin(x, 1)
arg_max = tf.argmax(x, 1)
unique = tf.unique(y)
diff = tf.setdiff1d(y, z)

with tf.Session() as session:
    print "Argmin = ", session.run(arg_min)
    print "Argmax = ", session.run(arg_max)

    print "Unique_values = ", session.run(unique)[0]
    print "Unique_idx = ", session.run(unique)[1]

    print "Setdiff_values = ", session.run(diff)[0]
    print "Setdiff_idx = ", session.run(diff)[1]

    print session.run(diff)[1]

Argmin =  [2 3 3 3]
Argmax =  [3 2 1 0]
Unique_values =  [1. 2. 5. 3. 7.]
Unique_idx =  [0 1 2 3 4]
Setdiff_values =  [5. 3. 7.]
Setdiff_idx =  [2 3 4]
[2 3 4]


In [5]:
data = pd.read_csv("../Python/Wavelet_Feature/EEG/Str_NaIn")
tar = np.ones((200,1))
tar1 = np.zeros((200,1))
target=np.concatenate((tar, tar1), axis=0)

 #prepare dataset for the machine learning techniques(use feature column headers)
from sklearn.model_selection import train_test_split

X = np.asarray(data[['0', '1', '2', '3', '4', '5']]) #feature vector column headers(wavelet bands)
y = target

train_dataset, test_dataset, train_labels, test_labels = train_test_split(X, y, test_size =0.3, random_state=0)


In [9]:

train_pl = tf.placeholder("float", [280, 6])
test_pl = tf.placeholder("float", [280,6])

knn_prediction = tf.reduce_sum(tf.abs(tf.add(train_pl, tf.negative(test_pl))), axis=1)

pred = tf.argmin(knn_prediction, 0)

with tf.Session() as tf_session:
    missed = 0

    for i in xrange(len(test_dataset)):
        knn_index = tf_session.run(pred, feed_dict={train_pl: train_dataset, test_pl: test_dataset[i]})

        print "Predicted class {} -- True class {}".format(train_labels[knn_index], test_labels[i])

        if train_labels[knn_index] != test_labels[i]:
            missed += 1

    tf.summary.FileWriter("../samples/article/logs", tf_session.graph)

print "Missed: {} -- Total: {}".format(missed, len(test_dataset))

ValueError: Cannot feed value of shape (6,) for Tensor u'Placeholder_7:0', which has shape '(280, 6)'